### ISSUE TITLE
Operaciones.Basicas.Lizbeth.Bautista

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-BautistaLizbeth#1]
[Sistemas.Numéricos.Liz.pdf](https://github.com/user-attachments/files/16844912/Sistemas.Numericos.Liz.pdf)

**Comment by LenninGS-0** [comment]
Portada: 25/25
Procedimiento:25/25
Figuras, ilustraciones y fotografías:25/25
Resultados y conclusiones:0/25 Falta la conclusión y los resultados
Final: 75/100

**Comment by josealfredo79** [comment]
Calificacion final 15
